const SAMPLE_NAMES = [
  { fname: "John", lname: "Doe" },
  { fname: "Jane", lname: "Smith" },
  { fname: "Michael", lname: "Johnson" },
  { fname: "Emily", lname: "Brown" },
  { fname: "William", lname: "Jones" },
  { fname: "Olivia", lname: "Garcia" },
  { fname: "James", lname: "Martinez" },
  { fname: "Emma", lname: "Robinson" },
  { fname: "Alexander", lname: "Clark" },
  { fname: "Isabella", lname: "Lewis" },
  { fname: "Daniel", lname: "Lee" },
  { fname: "Sophia", lname: "Walker" },
  { fname: "Matthew", lname: "Hall" },
  { fname: "Madison", lname: "Allen" },
  { fname: "Ethan", lname: "Young" },
  { fname: "Ava", lname: "Hernandez" },
  { fname: "Jacob", lname: "King" },
  { fname: "Mia", lname: "Wright" },
  { fname: "David", lname: "Lopez" },
  { fname: "Charlotte", lname: "Hill" },
  { fname: "Noah", lname: "Green" },
  { fname: "Liam", lname: "Adams" },
  { fname: "Grace", lname: "Baker" },
  { fname: "Chloe", lname: "Nelson" },
  { fname: "Logan", lname: "Carter" },
];

const JOBS = [
  "Software Engineer",
  "Data Analyst",
  "Project Manager",
  "Product Manager",
  "UX/UI Designer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "QA Engineer",
  "DevOps Engineer",
  "Network Engineer",
  "System Administrator",
  "Business Analyst",
  "Financial Analyst",
  "Marketing Manager",
  "Sales Representative",
  "Human Resources Manager",
  "Customer Service Representative",
  "Operations Manager",
  "Accountant",
  "Lawyer",
  "Doctor",
  "Nurse",
  "Teacher",
  "Chef",
];

export { SAMPLE_NAMES, JOBS };
